Skittyblock/aidoku-community-sources

- src/rust/wpcomics/build.ps1
- src/rust/wpcomics/sources/xoxocomics/src/lib.rs
- src/rust/wpcomics/template/src/helper.rs
- src/rust/wpcomics/template/src/template.rs
- Fix decimal chapter extraction (`Chapter 13.5` no longer gets converted to `Ch.135`)
- Windows build script use all native cmdlets, so the only thing required is `cargo`.
> Fix number parsing + Windows build script tweaks

- src/rust/wpcomics/build.sh
yeah that's it. fixes xoxocomics and other sources that use the default filter template.
> fix(wpcomics): copy default filter template

- .github/CONTRIBUTING.md
- LICENSE-APACHE
- LICENSE-MIT
- README.md
- Add a contribution guide
- Dual license under either of Apache 2.0 or MIT. This is what many Rust projects do, so I figured this choice would be fitting. Need all contributors to be on board though.
> Add contribution guide and dual-license (Apache-2.0 OR MIT)

- src/rust/en.nepnep/Cargo.lock
- src/rust/en.nepnep/res/source.json
- src/rust/en.nepnep/src/helper.rs
- src/rust/en.nepnep/src/lib.rs
- src/rust/en.nepnep/src/parser.rs
Accidentally pushed it to main, idc anymore
With bonus chapter deeplink support
Checklist:
> NepNep: Fix global search breaking manga directory

- src/rust/madara/sources/resetscans/res/source.json
- src/rust/madara/sources/resetscans/src/lib.rs
changed from manga to devmax
reset-scans.com/devmax/mangaid
Should not affect ids
Checklist:
> Changed source-path string

- src/rust/mangastream/sources/luminousscans/res/source.json
- src/rust/mangastream/sources/luminousscans/src/lib.rs
Luminous Scans updated their paths again, so quick fix
Checklist:
> fix(luminousscans): update path name again

- .github/CONTRIBUTING.md
Since we only accept Rust sources, it would be counterproductive to refer to other languages in the contribution guide.
> Remove references to languages other than Rust

- src/rust/multi.mangadex/res/source.json
- src/rust/multi.mangadex/src/parser.rs
MangaDex uses UTC timestamps, without this fix new chapters would not show up for hours because the timestamps were parsed as future times.
Checklist:
> fix(mangadex): parse dates in correct timezone

- .github/workflows/clippy.yaml
- .github/workflows/pr.yaml
original action uses `node12` (deprecated soon) and uses `set-output` (also deprecated soon) with no signs of fixing: jitterbit/get-changed-files#55
moving to a fork which does fix it: https://github.com/Ana06/get-changed-files
> Migrate jitterbit/get-changed-files to Ana06/get-changed-files

- src/rust/en.nepnep/res/source.json
- src/rust/en.nepnep/src/parser.rs
MangaSee uses special chapter prefixes as an homage to the series itself, I did not remove those, but I did remove all the generic chapter prefixes (that I've seen so far).
Checklist:
> fix(nepnep): remove more chapter prefixes and parse volumes

- src/rust/en.mangakatana/res/source.json
- src/rust/en.mangakatana/src/helper.rs
I can't believe I did this :(
This should fix chapter and manga id's being messed up and broken chapter images.
Checklist:
> fix(mangakatana): fix id parsing

- src/rust/mangastream/sources/swatmanga/res/source.json
- src/rust/mangastream/sources/swatmanga/src/lib.rs
- src/rust/mangastream/template/src/template.rs
> fix(mangastream): handle random chapter prefixes

- src/rust/multi.mangadex/res/source.json
- src/rust/multi.mangadex/src/lib.rs
- src/rust/multi.mangadex/src/parser.rs
Show all scanlator groups
Fallback to the uploader if there are no scanlator groups
Checklist:
> feat(mangadex): show multiple scanlators & uploader fallback

- src/rust/multi.batoto/res/source.json
- src/rust/multi.batoto/src/parser.rs
…sing.
Chapter string such as "Prolog" or "Notice" were producing an error while parsing leading to the function not outputting the list. Fixed the chapter number parsing at some places for string such as "V 1 C 1 [end]".
Checklist:
> Batoto: Fixed chapter list parsing

- src/rust/mangastream/sources/luminousscans/res/source.json
- src/rust/mangastream/sources/luminousscans/src/lib.rs
Luminous has hardcoded a 10 digit prefix for all their manhwas, so it is no longer possible to remove it. All previous library entries will have to be migrated as the ID's have changed.
Checklist:
> fix(luminousscans): remove has_permanent_manga_url

- src/rust/mangastream/sources/asurascans/res/source.json
- src/rust/mangastream/sources/flamescans/res/source.json
- src/rust/mangastream/template/src/helper.rs
Garbage was parsed as a u32, which could not handle large numbers
- fix(mangastream): parse ints as u64 instead of u32
- chore(asurascans): bump version
- chore(flamescans): bump version
I only bumped the sources that rely on permanent urls
silly me 😌
Checklist:
> fix(mangastream): parse ints as u64 instead of u32

- .github/CONTRIBUTING.md
- src/rust/en.nepnep/res/source.json
- src/rust/en.nepnep/src/lib.rs
- src/rust/en.nepnep/src/parser.rs
copied a lot of the code from what was already here such as using a static cache and refactored things along the way.
I couldn't find references to `.SearchResult > .SearchResultCover` in their website so I'd assumed it was removed
Checklist:
> en.nepnep: hot updates page

- src/rust/mangastream/sources/asurascans/res/source.json
- src/rust/mangastream/sources/asurascans/src/lib.rs
Unfortunately not all chapters on asura support permanent url's so some chapters break if this is enabled
This also means read history will be lost if asura rerolls the random int prefix (which they have been doing frequently) on the chapter url's as that will change the chapter id
- fix(asurascans): remove has_permanent_chapter_url
- chore(asurascans): bump version
Checklist:
> fix(asurascans): remove has_permanent_chapter_url

- src/rust/mangastream/sources/asurascans/res/source.json
- src/rust/mangastream/sources/asurascans/src/lib.rs
Asura is doing annoying stuff again 😕
Checklist:
> fix(asurascans): remove has_permanent_manga_url

- src/rust/zh.mangabz/Cargo.lock
- src/rust/zh.mangabz/res/source.json
- src/rust/zh.mangabz/src/lib.rs
- src/rust/zh.mangabz/src/parser.rs
This PR fixes the bug that the source is unable to search in Chinese.
I must be an idiot 🫠
I forgot I was developing a “Chinese” source, and didn’t percent-encode the search string. It’s funny that the site supports searching in Pinyin, so I wasn’t aware of that, and didn’t search in Chinese when testing.
And I always use `QueryParameters` in other sources, wth was I thinking 🥲
- Percent-encoded search string
- Updated source’s version
| Before | After | Source Info |
| :-: | :-: | :-: |
| ![IMG_CE9E85667801-1](https://github.com/Skittyblock/aidoku-community-sources/assets/64679454/95d9e31a-11e5-4473-8b0b-95ff46ddd211) | ![Simulator Screenshot - iPhone 14 Pro - 2023-05-20 at 00 55 02](https://github.com/Skittyblock/aidoku-community-sources/assets/64679454/069d2ecf-d393-4a9d-837e-a1f65bed95 …
> fix(`mangabz`): percent-encode search string

- src/rust/madara/sources/leviatanscans/res/source.json
- src/rust/madara/sources/leviatanscans/src/lib.rs
LeviatanScans english site uses Data URI images for chapters that are chopped up into 4 parts, 2 vertically and 2 horizontally. There is no way to stitch these images together in Aidoku, so effectively the english site is not usable for the foreseeable future. But the spanish site is working fine.
Checklist:
> Fix leviatanscans a bit

- src/rust/en.reaperscans/res/source.json
- src/rust/en.reaperscans/src/parser.rs
- src/rust/en.reaperscans/src/request_helper.rs
just reaper things
- Update selectors to not use classes
- Replace `expect` with `?`
- Bump version
Checklist:
> Fix reaperscans selectors

- src/rust/en.nepnep/Cargo.lock
- src/rust/en.nepnep/Cargo.toml
- src/rust/en.nepnep/res/filters.json
- src/rust/en.nepnep/res/source.json
- src/rust/en.nepnep/src/lib.rs
- src/rust/en.nepnep/src/model/mod.rs
- src/rust/en.nepnep/src/parser.rs
Had to do a decent amount of refactor so I could use `Vec` sort features. Couldn't use &str for deserialized struct values since serde requires ownership for string values with [escaped values](https://github.com/serde-rs/serde/issues/1413#issuecomment-494892266). I also couldn't use `Cow` since we don't have it in aidoku-rs
Checklist:
> nepnep: sort feature and refactor a lot of things

- src/rust/mangastream/Cargo.lock
- src/rust/mangastream/sources/asurascans/res/source.json
- src/rust/mangastream/sources/asurascans/src/lib.rs
- src/rust/mangastream/sources/luminousscans/res/source.json
- src/rust/mangastream/sources/luminousscans/src/lib.rs
- src/rust/mangastream/template/Cargo.toml
- src/rust/mangastream/template/src/helper.rs
- src/rust/mangastream/template/src/template.rs
Closes #382
This should solve the issues mangastream sources face whenever the urls or identifiers change. Theoretically, with postids, migration should no longer be necessary now, and chapter history won't be randomly reset.
I tested this with most english mangastream sources, and all was working well, with only 1 or 2 sources that did not support my postids implementation. That's why I have it as an opt-in setting for now, in the future this could become the default behavior if the majority of mangastream sources support it.
yes, it is a bit janky, but it works
Checklist:
> feat(mangastream): postid support

- src/rust/mangastream/sources/asurascans/res/source.json
- src/rust/mangastream/sources/asurascans/src/lib.rs
- src/rust/mangastream/sources/luminousscans/res/source.json
- src/rust/mangastream/sources/luminousscans/src/lib.rs
- src/rust/mangastream/template/src/template.rs
This makes it possible to use postids for manga entries and chapters separately.
I disabled postids for asura's chapters, since they have a very harsh 1 request per 10 sec rate limit on their api endpoint, which makes the extension extremely slow, and hangs migration on large libraries.
Downside is chapter history will be lost if asura changes chapter id's again, but that's better than the severe rate limit issues.
Checklist:
> feat(mangastream): split postids between manga entries and chapters

- src/rust/madara/sources/shinigami/res/source.json
- src/rust/madara/sources/shinigami/src/lib.rs
- Shinigami changed their domain
- Bump version
Closes #436
Checklist:
> Fix shinigami domain

- src/rust/es.tumangaonline/Cargo.lock
- src/rust/es.tumangaonline/res/source.json
- src/rust/es.tumangaonline/src/lib.rs
- Fixes the issue with the wrong chapter number at TuMangaOnline.
- Update the dependencies of TuMangaOnline source.
Checklist:
> Fix chapter number for TuMangaOnline.

- src/rust/madara/sources/firstkissmanga/Cargo.toml
- src/rust/madara/sources/firstkissmanga/res/source.json
- src/rust/madara/sources/firstkissmanga/src/lib.rs
Fix:
- Added base64 decode for `<script type="text/javascript" id="wp-manga-js-extra">`
Checklist:
> Fix 1stkissmanga get_chapter_list

- src/rust/multi.comick/res/source.json
Updated comick URL in source.json from comick.fun to comick.app
Every other instance is correct, just not the one in source.json 
Checklist:
> Fix comick url (from .fun to .app)

- src/rust/multi.komga/res/source.json
- src/rust/multi.komga/src/lib.rs
Fixing the probleme where chapter date where not displayed due to format change in date on "Komga Server" > 0.155.2
Checklist:
Fix #496
> Fix Komga chapter date not displayed

- src/rust/zh.copymanga/Cargo.lock
- src/rust/zh.copymanga/res/source.json
- src/rust/zh.copymanga/src/lib.rs
This PR fixes the bug that chapters are sorted incorrectly.
Chapters in the same group are already sorted in the JSON file; but the current sorting method (sort by date updated) will mess up the correct order.
- Updated dependencies in `Cargo.lock`
- Prevented chapters in the same group from being sorted
- Prefixed group name to chapter title
- Bumped version
| :-: | :-: |
| ![chapters_before](https://github.com/Skittyblock/aidoku-community-sources/assets/64679454/571adea4-72a3-4d32-b8c6-43e334b88b90) | ![chapters_after](https://github.com/Skittyblock/aidoku-community-sources/assets/64679454/4c1aaeff-3886-424e-92b8-2066641aac8e) |
| ![version_before](https://github.com/Skittyblock/aidoku-community-sources/assets/64679454/f64ecc45-2b9a-4bbe-8fbf-0fdea0d6ed2b) | …
> fix(copymanga): chapters sorted incorrectly

- src/rust/zh.copymanga/Cargo.lock
- src/rust/zh.copymanga/res/source.json
- src/rust/zh.copymanga/src/parser.rs
This PR fixes the bug that manga list is not loading properly.
Function `aidoku::std::json::parse` could not parse a string contains `\xa0`.
- Replaced `\xa0` with a space
- Updated source’s version
> fix(copymanga): manga list not loading properly

- src/rust/vi.blogtruyen/res/source.json
- src/rust/vi.blogtruyen/src/lib.rs
This PR fixes an issue where an invalid query selector (`a:contains([cuối])`) was used for the detection of `has_more`, resulting in only fetching the first page of results.
=> Should use the same selector as when no filters are provided.
https://github.com/Skittyblock/aidoku-community-sources/blob/6ac77a63245521809566382d391e08dc8c68ea2a/src/rust/vi.blogtruyen/src/lib.rs#L177-L180
Checklist:
> fix(blogtruyen): pagination not working in filtered list

- src/rust/multi.comick/res/source.json
- src/rust/multi.comick/src/lib.rs
Checklist:
ComicK moved from their `.app` domain to https://comick.cc (and https://api.comick.fun for the API).
Was unable to test the source, as the aidoku-cli just segfaults on my machine.
Should not cause any issues tho, as this is purely a url change in the strings.
Fixes #533
> Update to the new Url for ComicK

- src/rust/en.nepnep/res/source.json
- src/rust/en.nepnep/src/parser.rs
> fix(nepnep): unescape html entities in manga title

- src/rust/multi.myreadingmanga/Cargo.lock
- src/rust/multi.myreadingmanga/res/source.json
- src/rust/multi.myreadingmanga/src/lib.rs
This PR fixes the bug of the missing last chapter for manga with multiple chapters.
- Corrected the number of chapters
- Updated version
| :-: | :-: |
| ![before](https://github.com/Skittyblock/aidoku-community-sources/assets/64679454/e0c0fda1-db86-431c-87a8-8185aaa94462) | ![after](https://github.com/Skittyblock/aidoku-community-sources/assets/64679454/f3b84e33-ffff-4cf3-b27f-b9fbf5429988) |
> fix(myreadingmanga): missing last chapter

- src/rust/zh.boylove/Cargo.lock
- src/rust/zh.boylove/Cargo.toml
- src/rust/zh.boylove/res/source.json
- src/rust/zh.boylove/src/lib.rs
This PR fixes the bug that pages are split into pieces and shuffled.
- Returned original page urls
- Updated version
| :-: | :-: |
| ![before](https://github.com/Skittyblock/aidoku-community-sources/assets/64679454/90f10a0d-e530-4b7d-9bc1-69af9c091720) | ![after](https://github.com/Skittyblock/aidoku-community-sources/assets/64679454/20290cd4-39eb-46a6-95d3-4c9e0cc766e9) |
> fix(boylove): shuffled image pieces

- src/rust/multi.batoto/res/source.json
- src/rust/multi.batoto/src/parser.rs
Removed unnecessary token when fetching pages
Checklist:
> Fixed batoto source

- src/rust/multi.nhentai/res/source.json
- src/rust/multi.nhentai/src/lib.rs
I wanted to filter by all languages as this is the default behavior in the website and tachi.
Checklist:
> feat(nhentai): add all languages option

- src/rust/madara/Cargo.lock
- src/rust/madara/sources/manhuaplus/res/source.json
- src/rust/madara/sources/manhuaplus/src/lib.rs
- src/rust/madara/template/src/template.rs
Quick and dirty fix for some madara sources.
Since most sites work without this, it's not enabled by default, but it should work with all madara sources regardless, but I ain't taking that risk, it can be toggled on a case by case basis.
Closes #632
Checklist:
> fix(madara): use alternate method to get listings

- src/rust/en.zeroscans/res/source.json
- src/rust/en.zeroscans/src/helper.rs
- src/rust/en.zeroscans/src/parser.rs
Hopefully this is the last of the problems with this source.
Checklist:
> fix(zeroscans): handle edge case of old id's

- src/rust/zh.copymanga/Cargo.lock
- src/rust/zh.copymanga/Cargo.toml
- src/rust/zh.copymanga/res/source.json
- src/rust/zh.copymanga/src/decryptor.rs
- src/rust/zh.copymanga/src/helper/mod.rs
- src/rust/zh.copymanga/src/lib.rs
- src/rust/zh.copymanga/src/parser.rs
- src/rust/zh.copymanga/src/url.rs
This PR fixes the issue that the searching in `zh.copymanga` is not working.
- Closes #663
- Updated searching URL
- Updated version
- Rewrote enum `Url` for easier maintenance
- Not to panic!
|             |                                                             Before                                                              |                                                             After                                                              |
| :---------: | :-----------------------------------------------------------------------------------------------------------------------------: | :----------------------------------------------------------------------------------------------------------------------------: |
| **Search**  | …
> fix(copymanga): search not working

- src/rust/multi.mangadex/res/source.json
- src/rust/multi.mangadex/src/parser.rs
Looking at #25, it looks like the idea was to filter out chapters where the `externalUrl` is not null; however the current logic filters both when `externalUrl` is `null` and when it's a string (so essentially always I think?). Changed the logic to filter only chapters where `externalUrl` is a string.
A manga where chapters are filtered incorrectly is Houseki no Kuni ([API call](https://api.mangadex.org/manga/cade38b7-64c4-4a29-8e3c-8c283291d6c6/feed?order[volume]=desc&order[chapter]=desc&limit=500&contentRating[]=pornographic&contentRating[]=erotica&contentRating[]=suggestive&contentRating[]=safe&includes[]=scanlation_group&translatedLanguage[]=en), note how `externalUrl` is always null).
I haven't tested this with Aidoku itself (as I do not own a iOS/macOS device), but with a custom …
> fix(mangadex): do not fail chapter parsing if `externalUrl` is null

- src/rust/madara/sources/flowermanga/res/source.json
- src/rust/madara/sources/flowermanga/src/lib.rs
Changed the link to make the source work again.
Old: [flowermanga.com](https://flowermanga.com)
New: [flowermanga.net](https://flowermanga.net)
Checklist:
> Update FlowerManga website link

- src/rust/madara/sources/demonsect/res/source.json
- src/rust/madara/sources/demonsect/src/lib.rs
Changed the link to make the source work again.
Old: [demonsect.com.br](https://demonsect.com.br)
New: [dsectcomics.org](https://dsectcomics.org)
Checklist:
> Update DemonSect website link

- src/rust/zh.copymanga/Cargo.lock
- src/rust/zh.copymanga/res/source.json
- src/rust/zh.copymanga/src/url.rs
This PR fixes the bug that the source `zh.copymanga` is not working.
- Closes #717
The current domain is invalid.
- Removed invalid domains in `source.json`
- Updated the domain in `url.rs`
- Updated source version
|            |                                              Before                                               |                                               After                                              |
| :--------: | :-----------------------------------------------------------------------------------------------: | :----------------------------------------------------------------------------------------------: |
| **Browse** | ![browse-before](https://github.com/user-attachments/assets/6b00cad1-2120-4f8d-861f-e735d73446bc) | …
> fix(copymanga): source not working

- src/rust/en.tcbscans/res/source.json
- src/rust/en.tcbscans/src/lib.rs
**Summary:**
I added a constant for the website and updated the URL to the current TCB Scans URL.
The URL in `res/source.json` is now set to `https://tcbscans.com`, as this domain redirects to the current correct version of TCB Scans. If preferred, I can change it to `https://tcbscans.me`, which is the current working website.
This PR should make it easier to fix future TCB Scans URL changes.
**Checklist:**
**Screenshots:**
| TCB Overview                                                                                 | Manga Overview                                                                               | Chapter example                                                                              |
| ----------------------------------------------------------------------------------- …
> fix(tcb): add const for URL and change URL

- src/rust/mangastream/sources/manhwax/res/source.json
- src/rust/mangastream/sources/manhwax/src/lib.rs
Fixes #565 
I'm not sure if we should create a new source for this, or the current PR (of just updating the URL) works. I've tested it on a physical device - the website is slow but does work along with search functionalities. 
Checklist:
- [] ~Updated all sources' versions for template changes~ N/A
> Migrate manhwax to .org URL

- .gitignore
- src/rust/multi.myreadingmanga/Cargo.lock
- src/rust/multi.myreadingmanga/res/source.json
- src/rust/multi.myreadingmanga/src/lib.rs
This PR fixes the bug that the source `multi.myreadingmanga` cannot bypass Cloudflare on iPad.
- Closes #748
The current user agent cannot bypass Cloudflare on iPad.
- Updated source version
- Updated dependencies
- Updated user agent
| :-: | :-: |
| ![before-browse](https://github.com/user-attachments/assets/ca95859c-419f-434c-8665-a5db9a9fc2fa) | ![after-browse](https://github.com/user-attachments/assets/a1549a41-79a9-4fc6-9dd8-1c39d5263397) |
| ![before-info](https://github.com/user-attachments/assets/80c31ef3-8260-43db-b6b2-efa0d5aff978) | ![after-info](https://github.com/user-attachments/assets/be6e56ed-fb65-40e9-8aac-a5e246f53587) |
> fix(myreadingmanga): source not working on ipad

- src/rust/en.asurascans/res/source.json
- src/rust/en.asurascans/src/lib.rs
Filter out non ascii digits from parsed file name
If it breaks again, we can just stop trying to parse out the image index from the file name, and just rely on the dom's image element order.
Checklist:
> fix(asura): broken chapter image indices

- src/rust/multi.komga/res/source.json
- src/rust/multi.komga/src/lib.rs
Close #659
| Before |	After |
| ------- | ------ |
| ![image](https://github.com/user-attachments/assets/6f0db814-f62a-4519-a528-35d685680b2c) | ![image](https://github.com/user-attachments/assets/cc0ba7ba-a99a-4c44-800e-52a4ab3d0aa1) |
> fix(komga): Non-English search not working

- src/rust/zh.manhuagui/res/source.json
- src/rust/zh.manhuagui/src/decoder.rs
- src/rust/zh.manhuagui/src/parser.rs
> fix(manhuagui): incorrect chapter order

- src/rust/en.mangademon/res/source.json
- src/rust/en.mangademon/src/helper.rs
- src/rust/en.mangademon/src/lib.rs
- src/rust/en.mangademon/src/parser.rs
> fix(mangademon): rewrite most of the source to account for a site remake

- src/rust/multi.nhentai/res/source.json
- src/rust/multi.nhentai/src/helper.rs
> fix(nhentai): webp images

- src/rust/en.reaperscans/res/filters.json
- src/rust/en.reaperscans/res/source.json
- src/rust/en.reaperscans/src/parser.rs
Search was broken before since reaper's api doesn't like it when you send an empty url query param.
Also, made the sort filter an actual sort filter with support for acsending and descending order.
Checklist:
> fix(reaperscans): search and sorting

- src/rust/en.asurascans/res/source.json
- src/rust/en.asurascans/src/lib.rs
Checklist:
- [ x] Updated source's version for individual source changes
- [ x] Updated all sources' versions for template changes
- [ x] Set appropriate `nsfw` value
- [ x] Did not change `id` even if a source's name or language were changed
- [ x] Tested the modifications by running it on the simulator or a test device 
The method for finding and ordering the pages works by reading the `pages` object in the hydration JSON data, but I don't know how reliable that is. The fix works on the manhwa I have tested, but it could break.
> Fix: asura chapter and page list parsing

- src/rust/en.mangademon/res/source.json
- src/rust/en.mangademon/src/lib.rs
- updated the url
- looks like cloudflare was also blocking it, so i needed to add a user agent to requests
- aidoku should probably change the default user agent
closes #853
> fix(mangademon): new url and cf handling

- src/rust/en.hentaifox/res/source.json
- src/rust/en.hentaifox/src/helper.rs
- src/rust/en.hentaifox/src/lib.rs
previous version didn't account for older page images which still used jpeg. this one actually fetches the proper image extension. also fixed some issues with the urls being incorrect and next page loading not working.
> fix(hentaifox): older image and page loading

- src/rust/madara/sources/mangasorigines/res/filters.json
- src/rust/madara/sources/mangasorigines/res/source.json
- src/rust/madara/sources/mangasorigines/src/lib.rs
- src/rust/madara/template/src/helper.rs
madara template was fetching the id in some js, but looks like this source loads the js from base64 so it didn't exist. i think tachi's template takes the id from the chapter wrapper, which i added in. hopefully doesn't break any other sources...
also doesn't look like this source supports filtering by status / doesn't display status on the manga pages
closes #854
> fix(mangasorigines): details and chapter loading

- src/rust/en.tcbscans/res/source.json
- src/rust/en.tcbscans/src/lib.rs
`tcbscans.me` now redirects to `tcbonepiecechapters.com`.
Checklist:
Screenshots: 
| TCB Overview                                                                                 | Manga Overview                                                                               | Chapter example                                                                              |
| -------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------- |
| ![IMG_2843](https://github.com/user-attachments/assets/02a7ed0a-267e-442f-94b7-b5b2c40086d6) | …
> fix(tcb): Update URL

- src/rust/multi.myreadingmanga/Cargo.lock
- src/rust/multi.myreadingmanga/res/source.json
- src/rust/multi.myreadingmanga/src/lib.rs
This PR fixes the bug that the images in the source `multi.myreadingmaga` are not loading.
The website changed the attribute that contained the image URL.
- Fixed the issue that images failed to load
|                                              Before                                               |                                              After                                               |
|:-----------------------------------------------------------------------------------------------: |:----------------------------------------------------------------------------------------------: |
|![browse-before](https://github.com/user-attachments/assets/6550ceaf-efdc-45ab-bd8a-0ebad06f8f6b) |![browse-after](https://github.com/user-attachments/assets/ff8d2a93-a9ed-4970-bc3b-a2c58b3a3818) | …
> fix(myreadingmanga): images not loading

- src/rust/zh.copymanga/Cargo.lock
- src/rust/zh.copymanga/res/source.json
- src/rust/zh.copymanga/src/url.rs
This PR fixes the issue where the original domain has expired.
- Closes #922
The original domain has expired.
- Fixed the source
- Removed expired domain for deep linking
| :-: | :-: |
| ![before-browse](https://github.com/user-attachments/assets/1f74172f-c24b-4c63-9666-cea79dbc659e) | ![after-browse](https://github.com/user-attachments/assets/0cf4c6a5-cb6e-4987-907c-2922863bfbb6) |
| ![before-info](https://github.com/user-attachments/assets/a05d6739-9e9a-49e6-870b-64f61a076664) | ![after-info](https://github.com/user-attachments/assets/34c1de6d-3f3f-4767-9b56-ebcc1289507b) |
> fix(copymanga): domain changed

- src/rust/mangabox/sources/mangabat/res/source.json
- src/rust/mangabox/sources/manganato/res/source.json
- src/rust/mangabox/sources/manganato/src/lib.rs
- src/rust/mangabox/template/src/helper.rs
- src/rust/mangabox/template/src/template.rs
- updated manganato url (natomanga.com has some weird cloudflare issues i couldn't get past)
- fixed some special character search encoding
- fixed `has_more` for manga pages
- fixed listings for manganato and mangabat
closes #918
> fix(mangabox): handle multiple pages and listings

- src/rust/mmrcms/sources/mangaid/Cargo.toml
- src/rust/mmrcms/sources/mangaid/src/lib.rs
- src/rust/mmrcms/template/Cargo.toml
- src/rust/mmrcms/template/src/lib.rs
- src/rust/mmrcms/template/src/template.rs
- src/rust/multi.mangadex/Cargo.toml
- src/rust/multi.mangadex/src/helper.rs
- src/rust/multi.mangadex/src/lib.rs
- src/rust/vi.hentaivn/Cargo.toml
- src/rust/vi.hentaivn/src/lib.rs
closes #1013 
let chains are stable now, so building with a newer nightly rust will fail compilation when using `#![feature(let_chains)]`.
I didn't update source versions since there should be no source changes, only fixing compilation.
> chore: fix sources using let chains
