src/as/vi.hentaivn/src/parser.ts

fix(vi.hentaivn): genre filter

---

src/rust/multichan/sources/hentaichan/res/source.json
src/rust/multichan/sources/mangachan/res/source.json
src/rust/multichan/sources/yaoichan/res/source.json
src/rust/multichan/template/src/template.rs

the funny cyrillic characters messes things up

fix: multichan fix for search by tags

---

src/as/es.tumangaonline/package-lock.json
src/as/es.tumangaonline/res/settings.json
src/as/es.tumangaonline/src/TuMangaOnlineSource.ts
src/as/es.tumangaonline/src/index.ts

Add rate limiter for TuMangaOnline

---

src/rust/madara/sources/coloredmanga/res/source.json
src/rust/madara/sources/fecomic/res/source.json
src/rust/madara/sources/hentaicb/res/source.json
src/rust/madara/sources/lilymanga/res/source.json
src/rust/madara/sources/mangatx/res/source.json
src/rust/madara/sources/manhuaplus/res/source.json
src/rust/madara/sources/reaperscans/res/source.json
src/rust/madara/sources/resetscans/res/source.json
src/rust/madara/sources/toonily/res/filters.json
src/rust/madara/sources/toonily/res/source.json
src/rust/madara/sources/yocomic/res/source.json
src/rust/madara/template/src/helper.rs
src/rust/madara/template/src/template.rs

changed to get requests, fixed time, fixed chapter names, fixed covers, fixed toonily filter 
Checklist:

Madara optimization

---

src/rust/madara/sources/coloredmanga/res/source.json
src/rust/madara/sources/fecomic/res/source.json
src/rust/madara/sources/hentaicb/res/source.json
src/rust/madara/sources/lilymanga/res/source.json
src/rust/madara/sources/mangatx/res/source.json
src/rust/madara/sources/manhuaplus/res/source.json
src/rust/madara/sources/reaperscans/res/source.json
src/rust/madara/sources/resetscans/res/source.json
src/rust/madara/sources/toonily/res/source.json
src/rust/madara/sources/yocomic/res/source.json
src/rust/madara/template/src/helper.rs
src/rust/madara/template/src/template.rs

changed back to ajax chapter request
Checklist:

madara chapter fix

---

src/rust/en.nepnep/res/source.json
src/rust/en.nepnep/src/helper.rs
src/rust/en.nepnep/src/lib.rs
src/rust/en.nepnep/src/parser.rs

NepNep: Update cover base URL

---

src/rust/en.webtoon/Cargo.lock
src/rust/en.webtoon/Cargo.toml
src/rust/en.webtoon/res/source.json
src/rust/en.webtoon/src/lib.rs
src/rust/en.webtoon/src/parser.rs

* remove chrono dependency
* fix clippy lints
* fix volume number
* ~~pre-allocate vectors when possible~~
Checklist:

fixes for webtooon

---

src/rust/madara/sources/coloredmanga/res/source.json
src/rust/madara/sources/fecomic/res/source.json
src/rust/madara/sources/hentaicb/res/source.json
src/rust/madara/sources/lilymanga/res/source.json
src/rust/madara/sources/mangatx/res/source.json
src/rust/madara/sources/manhuaplus/res/source.json
src/rust/madara/sources/reaperscans/res/source.json
src/rust/madara/sources/resetscans/res/source.json
src/rust/madara/sources/toonily/res/source.json
src/rust/madara/sources/yocomic/res/source.json
src/rust/madara/template/src/template.rs

Added header for madara cookie

---

src/rust/multi.mangadex/res/source.json
src/rust/multi.mangadex/src/helper.rs
src/rust/multi.mangadex/src/parser.rs

MangaDex: Hopefully fixes memory leaks from date objects

---

src/as/vi.hentaivn/res/source.json
src/as/vi.hentaivn/src/constants.ts

HentaiVN: Update base URL

---

src/rust/wpcomics/Cargo.lock
src/rust/wpcomics/sources/readcomicsbook/res/source.json
src/rust/wpcomics/sources/readcomicsbook/src/lib.rs

ReadComicsBook: Fix page list not loading

---

.github/workflows/clippy.yaml
.github/workflows/supporting/annotations.jq
.github/workflows/supporting/summary.jq
src/rust/vi.blogtruyen/src/lib.rs

[Demo workflow run.](https://github.com/Skittyblock/aidoku-community-sources/actions/runs/2774398736)
This workflow also pushes annotations:

Add Clippy linting for Rust PRs

---

.github/workflows/build.yaml
.github/workflows/pr.yaml

[ci] remove dependency on linuxbrew

---

src/rust/madara/sources/coloredmanga/res/source.json
src/rust/madara/sources/coloredmanga/src/lib.rs

fix(coloredmanga): update source path

---

src/rust/mangastream/sources/luminousscans/res/source.json
src/rust/mangastream/sources/luminousscans/src/lib.rs

fix(luminousscans): update pathname

---

src/rust/madara/sources/manhuaplus/res/source.json
src/rust/madara/sources/manhuaplus/src/lib.rs

fix(manhuaplus): fix broken images

---

src/as/vi.hentaivn/res/source.json
src/as/vi.hentaivn/src/constants.ts
src/rust/wpcomics/sources/nettruyen/res/source.json
src/rust/wpcomics/sources/nettruyen/src/lib.rs

They change the domains for like every one or two weeks which is annoying
Checklist:

Nettruyen and HentaiVN URL update

---

src/rust/madara/sources/lhtranslation/res/source.json
src/rust/madara/sources/lhtranslation/src/lib.rs

fix(lhtranslation): set correct content rating

---

src/rust/madara/sources/leviatanscans/res/source.json
src/rust/madara/sources/leviatanscans/src/lib.rs

fix(leviatanscans): update source path

---

src/rust/mangastream/sources/cosmicscans/res/source.json
src/rust/mangastream/sources/cosmicscans/src/lib.rs

fix(cosmicscans): fix broken covers in details page

---

src/rust/mangastream/sources/flamescans/res/source.json
src/rust/mangastream/sources/flamescans/src/lib.rs
src/rust/mangastream/sources/luminousscans/res/source.json
src/rust/mangastream/sources/luminousscans/src/lib.rs
src/rust/mangastream/template/src/helper.rs
src/rust/mangastream/template/src/template.rs

feat(mangastream): add support for permanent urls

---

src/rust/madara/sources/manhuaus/res/source.json
src/rust/madara/sources/manhuaus/src/lib.rs
src/rust/madara/template/src/helper.rs

fix(manhuaus): fix broken images for some series

---

src/rust/madara/sources/coloredmanga/res/source.json
src/rust/madara/sources/coloredmanga/src/lib.rs

fix(coloredmanga): update source_path

---

src/rust/madara/sources/resetscans/res/source.json
src/rust/madara/sources/resetscans/src/lib.rs

fix(resetscans): update description selector

---

src/rust/madara/sources/coloredmanga/res/source.json
src/rust/madara/sources/disasterscans/res/source.json
src/rust/madara/sources/fecomic/res/source.json
src/rust/madara/sources/hentaicb/res/source.json
src/rust/madara/sources/hscans/res/source.json
src/rust/madara/sources/isekaiscan/res/source.json
src/rust/madara/sources/leviatanscans/res/source.json
src/rust/madara/sources/lhtranslation/res/source.json
src/rust/madara/sources/lhtranslation/src/lib.rs
src/rust/madara/sources/lilymanga/res/source.json
src/rust/madara/sources/mangatx/res/source.json
src/rust/madara/sources/manhuafast/res/source.json
src/rust/madara/sources/manhuaplus/res/source.json
src/rust/madara/sources/manhuaus/res/source.json
src/rust/madara/sources/manhwaid/res/source.json
src/rust/madara/sources/mmscans/res/source.json
src/rust/madara/sources/neoxscans/res/source.json
src/rust/madara/sources/nightcomic/res/source.json
src/rust/madara/sources/reaperscansid/res/source.json
src/rust/madara/sources/resetscans/res/source.json
src/rust/madara/sources/setsuscans/res/source.json
src/rust/madara/sources/toonily/res/source.json
src/rust/madara/sources/twilightscans/res/source.json
src/rust/madara/sources/yocomic/res/source.json
src/rust/madara/template/src/template.rs

fix(madara): improve madara template

---

src/rust/multi.mangadex/res/filters.json
src/rust/multi.mangadex/res/settings.json
src/rust/multi.mangadex/res/source.json
src/rust/multi.mangadex/src/parser.rs

fix(mangadex): properly title oneshots

---

src/rust/mangastream/sources/sushiscan/res/filters.json
src/rust/mangastream/sources/sushiscan/res/source.json
src/rust/mangastream/sources/sushiscan/src/lib.rs

fix(sushiscan): update url

---

src/rust/en.webtoon/res/source.json
src/rust/en.webtoon/src/parser.rs

fix(webtoon): fix titles, volumes and vertical covers

---

src/rust/en.nepnep/res/settings.json
src/rust/en.nepnep/res/source.json
src/rust/en.nepnep/src/parser.rs

fix(nepnep): parse titles properly

---

src/rust/en.webtoon/res/source.json
src/rust/en.webtoon/src/parser.rs

fix(webtoon): fix cover sizes and parse seasons/volumes

---

src/rust/wpcomics/sources/nettruyen/res/source.json
src/rust/wpcomics/sources/nettruyen/src/helper.rs
src/rust/wpcomics/sources/nettruyen/src/lib.rs
src/rust/wpcomics/sources/readcomicsbook/src/helper.rs
src/rust/wpcomics/sources/readcomicsfree/src/helper.rs
src/rust/wpcomics/sources/xoxocomics/src/helper.rs

[NetTruyen] Fix manga search

---

.github/workflows/build.yaml

only trigger the build workflow on main branch

---

src/rust/madara/sources/coloredmanga/res/source.json
src/rust/madara/sources/disasterscans/res/source.json
src/rust/madara/sources/fecomic/res/source.json
src/rust/madara/sources/hentaicb/res/source.json
src/rust/madara/sources/hscans/res/source.json
src/rust/madara/sources/isekaiscan/res/source.json
src/rust/madara/sources/leviatanscans/res/source.json
src/rust/madara/sources/lhtranslation/res/source.json
src/rust/madara/sources/lilymanga/res/source.json
src/rust/madara/sources/mangatx/res/source.json
src/rust/madara/sources/manhuafast/res/source.json
src/rust/madara/sources/manhuaplus/res/source.json
src/rust/madara/sources/manhuaus/res/source.json
src/rust/madara/sources/manhwaid/res/source.json
src/rust/madara/sources/mmscans/res/source.json
src/rust/madara/sources/neoxscans/res/source.json
src/rust/madara/sources/nightcomic/res/source.json
src/rust/madara/sources/reaperscansar/res/source.json
src/rust/madara/sources/reaperscansid/res/source.json
src/rust/madara/sources/resetscans/res/source.json
src/rust/madara/sources/setsuscans/res/source.json
src/rust/madara/sources/toonily/res/source.json
src/rust/madara/sources/twilightscans/res/source.json
src/rust/madara/sources/yocomic/res/source.json
src/rust/madara/template/src/template.rs

fix(madara): handle more status syntaxes

---

src/rust/en.nepnep/res/source.json
src/rust/en.nepnep/src/parser.rs

fix(nepnep): fix chapter volume parsing

---

src/rust/madara/sources/coloredmanga/res/source.json
src/rust/madara/sources/coloredmanga/src/lib.rs

Coloredmanga: Added modify_image_request

---

src/rust/mangaworld/res/filters.json
src/rust/mangaworld/sources/mangaworld/res/source.json
src/rust/mangaworld/sources/mangaworldadult/res/source.json
src/rust/mangaworld/template/src/template.rs

Someone placed the style at the wrong place somehow
Checklist:

mangaworld chapter image not loading fix

---

src/rust/en.mangafox/res/source.json
src/rust/en.mangafox/src/lib.rs
src/rust/en.mangafox/src/parser.rs

Mangafox fix

---

src/rust/madara/Cargo.lock
src/rust/madara/sources/hiperdex/res/settings.json
src/rust/madara/sources/hiperdex/res/source.json
src/rust/madara/sources/hiperdex/src/lib.rs

fix: hiperdex update domain & domain selector

---

src/rust/en.mangakatana/Cargo.lock
src/rust/en.mangakatana/res/filters.json
src/rust/en.mangakatana/res/source.json
src/rust/en.mangakatana/src/parser.rs

- fix(mangakatana): handle pagination redirects
- chore(mangakatana): bump version
- chore(mangakatana): exclude nsfw by default
- deps: update dependencies
Checklist:

fix(mangakatana): handle pagination redirects

---

src/rust/multi.nhentai/res/source.json
src/rust/multi.nhentai/src/lib.rs

Fix NHentai User-Agent

---

src/rust/mangastream/sources/asurascans/res/source.json
src/rust/mangastream/sources/asurascans/src/lib.rs

fix(asurascans): use permanent chapter urls

---

src/rust/mangastream/sources/asurascans/src/lib.rs

fix(asurascans): use permanent_manga_url

---

src/rust/wpcomics/sources/nettruyen/res/source.json
src/rust/wpcomics/sources/nettruyen/src/lib.rs
src/rust/wpcomics/template/src/template.rs

Checklist:
just to fix for vus.#6370 lol
cheers

fix: nettruyen

---

src/rust/vi.hentaivn/res/source.json
src/rust/vi.hentaivn/src/lib.rs

HentaiVN: Fix pages not loading

---

src/rust/zh.baozimanhua/Cargo.lock
src/rust/zh.baozimanhua/res/filters.json
src/rust/zh.baozimanhua/res/source.json
src/rust/zh.baozimanhua/src/lib.rs
src/rust/zh.baozimanhua/src/parser.rs

This PR fixes the source **baozimanhua** failing to load chapter.
The site changed chapters domain and pages layout, causing the source to fail to load chapter.
* Code readability
* `Chapter` url
* `get_page_list()`
* `nsfw` value
* Source version
This fix was tested on both simulator and TestFlight app.
| Source Version | `Chapter` | `get_page_list()` |
| :-: | :-: | :-: | 
| ![Simulator Screenshot - iPhone 14 Pro - 2023-05-13 at 16 04 33](https://github.com/Skittyblock/aidoku-community-sources/assets/64679454/d27f3786-3465-4f31-a9fa-cf7b05c2d4d8) | ![Simulator Screenshot - iPhone 14 Pro - 2023-05-13 at 16 05 59](https://github.com/Skittyblock/aidoku-community-sources/assets/64679454/5c903af0-d68c-48e7-9e52-e017edb0f8c6) | ![Simulator Screenshot - iPhone 14 Pro - 2023-05-14 at 16 02 …

fix(baozimanhua): fix chapters parsing

---

src/rust/mangadventure/Cargo.lock
src/rust/mangadventure/scripts/filters.sh
src/rust/mangadventure/sources/arcrelight/Cargo.toml
src/rust/mangadventure/sources/arcrelight/res/filters.json
src/rust/mangadventure/sources/arcrelight/res/source.json
src/rust/mangadventure/sources/assortedscans/Cargo.toml
src/rust/mangadventure/sources/assortedscans/res/filters.json
src/rust/mangadventure/sources/assortedscans/res/source.json
src/rust/mangadventure/template/Cargo.toml
src/rust/mangadventure/template/src/lib.rs

MangAdventure: support more series statuses

---

src/rust/wpcomics/sources/nettruyen/res/source.json
src/rust/wpcomics/sources/nettruyen/src/lib.rs

Checklist:
Closes https://github.com/Skittyblock/aidoku-community-sources/issues/360

wpcomics - nettruyen url update

---

src/rust/multi.simplyhentai/Cargo.lock
src/rust/multi.simplyhentai/res/source.json
src/rust/multi.simplyhentai/src/lib.rs
src/rust/multi.simplyhentai/src/parser.rs

fix(simplyhentai): incorrect page count

---

src/rust/en.hentaifox/Cargo.lock
src/rust/en.hentaifox/Cargo.toml
src/rust/en.hentaifox/res/source.json
src/rust/en.hentaifox/src/helper.rs
src/rust/en.hentaifox/src/lib.rs

fix(hentaifox): incorrect search page count

---

src/rust/wpcomics/sources/truyenqq/res/source.json
src/rust/wpcomics/sources/truyenqq/src/lib.rs

wpcomics truyenqq url update

---

src/rust/madara/Cargo.lock
src/rust/madara/build.sh
src/rust/madara/sources/shinigami/src/lib.rs

Hopefully fix the madara sources installation error
Checklist:

Update Madara cargo

---

src/rust/mangastream/sources/asurascans/res/source.json
src/rust/mangastream/sources/asurascans/src/helper.rs

Fix: Update Asura Scans Url

---

src/rust/vi.blogtruyen/res/source.json
src/rust/vi.blogtruyen/src/lib.rs

Update BlogTruyen source URL

---

src/rust/mangastream/Cargo.toml
src/rust/mangastream/sources/sushiscan/src/lib.rs
src/rust/mangastream/template/src/helper.rs
src/rust/mangastream/template/src/template.rs

Fix Sushi Scan

---

src/rust/mangastream/sources/asurascans/res/source.json
src/rust/mangastream/sources/asurascans/src/helper.rs

Update asurascans url

---

src/rust/madara/Cargo.lock
src/rust/madara/sources/setsuscans/Cargo.toml
src/rust/madara/sources/setsuscans/res/source.json
src/rust/madara/sources/setsuscans/src/lib.rs
src/rust/madara/sources/shinigami/src/lib.rs

fix(setsuscans): remove get_manga_id override

---

src/rust/madara/sources/firstkissmanga/res/source.json
src/rust/madara/sources/firstkissmanga/src/lib.rs

1ST KISS MANGA update

---

src/rust/multi.webtoon/res/source.json
src/rust/multi.webtoon/src/helper.rs
src/rust/multi.webtoon/src/parser.rs

fix(webtoon): fix canvas series

---

src/rust/mangastream/sources/asurascans/res/source.json
src/rust/mangastream/sources/asurascans/src/helper.rs

Changed from asuracomics.com to asuracomics.gg 
:)

Updated Asura URL Again

---

src/rust/en.reaperscans/res/source.json
src/rust/en.reaperscans/src/parser.rs

fix(reaperscans): update image selector

---

src/rust/mangastream/sources/asurascans/res/source.json
src/rust/mangastream/sources/asurascans/src/helper.rs

Asura URL Update

---

src/rust/madara/sources/firstkissmanga/Cargo.toml
src/rust/madara/sources/firstkissmanga/res/source.json
src/rust/madara/sources/firstkissmanga/src/lib.rs

This reverts commit 38e9680e9f5f0bb174448b49b1020b7c8cb554be.
Checklist:

Revert 1stkissmanga id changes

---

src/rust/mangastream/sources/asurascans/res/source.json
src/rust/mangastream/sources/asurascans/src/lib.rs

| --- | --- |
| ![before](https://github.com/Skittyblock/aidoku-community-sources/assets/20971850/97314f00-2404-4738-9d4e-91a976328ada) | ![after](https://github.com/Skittyblock/aidoku-community-sources/assets/20971850/d4cd1f0d-15a3-49a1-bc79-3f6b704962de) |
Checklist:

fix(asurascans): remove broken leading image

---

src/rust/mangastream/sources/luminousscans/res/source.json
src/rust/mangastream/sources/luminousscans/src/lib.rs

fix(luminousscans): update url

---

src/rust/es.tumangaonline/res/source.json
src/rust/es.tumangaonline/src/lib.rs

Checklist:
Closes [#503](https://github.com/Skittyblock/aidoku-community-sources/issues/503)

Change referer TuMangaOnline

---

src/rust/en.zeroscans/Cargo.lock
src/rust/en.zeroscans/Cargo.toml
src/rust/en.zeroscans/res/source.json
src/rust/en.zeroscans/src/lib.rs

Checklist:
did the zero scan url change thing

zero scans url change

---

src/rust/wpcomics/sources/nettruyen/res/source.json
src/rust/wpcomics/sources/nettruyen/src/lib.rs

Update nettruyen domain

---

src/rust/en.nepnep/res/source.json
src/rust/en.nepnep/src/lib.rs

fix(nepnep): int overflow issue causing chapter to repeat

---

src/rust/multi.batoto/Cargo.lock
src/rust/multi.batoto/res/source.json
src/rust/multi.batoto/src/parser.rs

image array var name was changed

---

src/rust/multi.myreadingmanga/res/source.json
src/rust/multi.myreadingmanga/src/lib.rs

This PR fixes the bug that images are not loading.
- Updated selectors for images
- Updated version

fix(myreadingmanga): images not loading

---

src/rust/wpcomics/sources/nettruyen/res/source.json
src/rust/wpcomics/sources/nettruyen/src/lib.rs
src/rust/wpcomics/sources/truyenqq/res/source.json
src/rust/wpcomics/sources/truyenqq/src/lib.rs

wpcomics (truyenqq and nettruyen) update domain name

---

src/rust/mangastream/sources/aresmanga/res/source.json
src/rust/mangastream/sources/aresmanga/src/lib.rs

fix (AresManga) domain name update

---

src/rust/mangadventure/Cargo.lock
src/rust/mangadventure/sources/arcrelight/Cargo.toml
src/rust/mangadventure/sources/arcrelight/res/source.json
src/rust/mangadventure/sources/assortedscans/Cargo.toml
src/rust/mangadventure/sources/assortedscans/res/source.json
src/rust/mangadventure/template/Cargo.toml
src/rust/mangadventure/template/src/lib.rs

feat(mangadventure): exclude licensed series

---

src/rust/multichan/sources/hentaichan/res/source.json
src/rust/multichan/sources/hentaichan/src/lib.rs

Update Hentaichan Adress

---

src/rust/madara/sources/resetscans/res/source.json
src/rust/madara/sources/resetscans/src/lib.rs

reset scans url change (no aidoku.exe this time)

---

src/rust/madara/sources/lilymanga/res/source.json
src/rust/madara/sources/lilymanga/src/lib.rs

Updated lilymanga source

---

src/rust/wpcomics/sources/nettruyen/res/source.json
src/rust/wpcomics/sources/nettruyen/src/lib.rs

fix(nettruyen): update domain

---

src/rust/multi.comick/res/source.json
src/rust/multi.comick/src/lib.rs
src/rust/multi.comick/src/parser.rs

fix(comick): genres not loading

---

src/rust/multi.nhentai/res/source.json
src/rust/multi.nhentai/src/lib.rs

Fixed useragent

---

src/rust/wpcomics/sources/nettruyen/res/source.json
src/rust/wpcomics/sources/nettruyen/src/lib.rs

fix(wpcomics.nettruyen): update domain url

---

src/rust/en.omegascans/res/filters.json
src/rust/en.omegascans/res/source.json
src/rust/en.omegascans/src/parser.rs

Fixed omegascans

---

src/rust/mangabox/sources/mangabat/res/source.json
src/rust/mangabox/sources/mangabat/src/lib.rs

Checklist:
fixes https://github.com/Skittyblock/aidoku-community-sources/issues/611

Fixed mangabat url

---

src/rust/ru.readmanga/res/source.json
src/rust/ru.readmanga/src/parser.rs

Added removing not needed part of javascript in parser.rs tha loaded incorrect image links with scrapped html.
* Closes https://github.com/Skittyblock/aidoku-community-sources/issues/560
Checklist:

Ru ReadManga source loading Fix

---

src/rust/en.mangademon/res/source.json
src/rust/en.mangademon/src/helper.rs
src/rust/en.mangademon/src/lib.rs
src/rust/en.mangademon/src/parser.rs

fix(mangademon): update url

---

src/rust/mangastream/Cargo.lock
src/rust/mangastream/sources/asurascans/res/source.json
src/rust/mangastream/sources/asurascans/src/helper.rs

fix(asurascans): update url

---

src/rust/wpcomics/sources/nettruyen/res/source.json
src/rust/wpcomics/sources/nettruyen/src/lib.rs

fix(nettruyen): update domain name

---

src/rust/en.zeroscans/res/source.json
src/rust/en.zeroscans/src/parser.rs

This should fix the app crashing issue 🫠
Checklist:

fix(zeroscans): stop using `expect`

---

src/rust/vi.hentaivn/res/source.json
src/rust/vi.hentaivn/src/lib.rs

Update Hentaivn Url

---

src/rust/en.omegascans/res/source.json
src/rust/en.omegascans/src/parser.rs

Omega Scans: Added a 'newest' listing and fixed missing last image

---

src/rust/mangastream/sources/luminousscans/res/source.json
src/rust/mangastream/sources/luminousscans/src/lib.rs

Checklist:
Deals with issue 686
[@https://github.com/Skittyblock/aidoku-community-sources/issues/686](https://github.com/Skittyblock/aidoku-community-sources/issues/686)

Updated luminous url

---

src/rust/madara/sources/theblank/res/source.json
src/rust/madara/sources/theblank/src/lib.rs

Fixed The Blank cloudflare and images not loading

---

src/rust/en.asurascans/res/source.json
src/rust/en.asurascans/src/lib.rs

fix(asura): broken covers and chapters

---

src/rust/madara/sources/coloredmanga/res/source.json
src/rust/madara/sources/coloredmanga/src/lib.rs

Checklist:
- [  ] Updated all sources' versions for template changes
- [  ] Set appropriate `nsfw` value
- [  ] Tested the modifications by running it on the simulator or a test device

fix(coloredmanga): update url 

---

src/rust/en.asurascans/res/source.json
src/rust/en.asurascans/src/lib.rs

fix(asura): broken chapters

---

src/rust/mangastream/sources/tenshi/res/source.json
src/rust/mangastream/sources/tenshi/src/lib.rs
src/rust/mangastream/sources/voidscans/res/source.json
src/rust/mangastream/sources/voidscans/src/lib.rs

* Update Voidscans url
* Update Tenshi url
* Update Voidscans Source and Version
* Update Tenshi Source and Version
Checklist:
Closes #728 and #761

fix(VoidScans & Tenshi): Update url

---

src/rust/mangastream/sources/luminousscans/res/source.json
src/rust/mangastream/sources/luminousscans/src/lib.rs

fix(LuminousScans) - Change URL

---

src/rust/madara/sources/resetscans/res/source.json
src/rust/madara/sources/resetscans/src/lib.rs

fix(ResetScans): Update URL

---

src/rust/es.tumangaonline/res/source.json
src/rust/es.tumangaonline/src/lib.rs

fix(TUMangaOnline) : fix url Change.

---

src/rust/multi.libgroup/sources/mangalib/res/source.json
src/rust/multi.libgroup/template/src/parser.rs
src/rust/multi.libgroup/template/src/template.rs

fix(mangalib): update URL to manga & one more thing

---

src/rust/en.asurascans/res/source.json
src/rust/en.asurascans/src/lib.rs

fix(asurascans): fix chapter names and page list parsing

---

src/rust/wpcomics/sources/xoxocomics/res/source.json
src/rust/wpcomics/sources/xoxocomics/src/helper.rs
src/rust/wpcomics/sources/xoxocomics/src/lib.rs

Xoxocomic search and genre filtering fixes

---

src/rust/en.reaperscans/res/source.json
src/rust/en.reaperscans/src/parser.rs

Fixes duplicate chapter numbers and adds chapter titles
Checklist:

fix(reaper): chapter titles and numbers

---

src/rust/en.weebcentral/src/lib.rs

fix(weebcentral): covers not being fetched

---

src/rust/en.weebcentral/res/source.json
src/rust/en.weebcentral/src/helper.rs
src/rust/en.weebcentral/src/lib.rs

and remove special characters from searching (bc the tachi source does it)
closes #857

fix(weebcentral): chapter list not loading

---

src/rust/en.hentaifox/res/source.json
src/rust/en.hentaifox/src/lib.rs

fix(hentaifox): switch to webp page images

---

src/rust/en.hentai2read/res/source.json
src/rust/en.hentai2read/src/helper.rs
src/rust/en.hentai2read/src/parser.rs

fix(hentai2read): list cover images

---

src/rust/mangastream/sources/tenshi/res/source.json
src/rust/mangastream/sources/tenshi/src/lib.rs
src/rust/mangastream/template/src/helper.rs

fix(tenshi): update url

---

src/rust/madara/sources/hiperdex/res/source.json
src/rust/madara/sources/hiperdex/src/lib.rs

this source is abysmally slow for me
closes #789
closes #445

fix(hiperdex): cf handling

---

src/rust/mangastream/sources/phenixscans/res/source.json
src/rust/mangastream/sources/phenixscans/src/lib.rs
src/rust/mangastream/template/src/helper.rs

fix(phenixscans): cf handling and details fetching

---

src/rust/mangastream/sources/swatmanga/res/source.json
src/rust/mangastream/sources/swatmanga/src/lib.rs
src/rust/mangastream/template/src/template.rs

fix(swatmanga): update url and page loading

---

src/rust/en.mangafox/res/source.json
src/rust/en.mangafox/src/lib.rs
src/rust/en.mangafox/src/parser.rs

this source should probably be rewritten since it looks like there are other issues, but this should fix the search issue
closes #810

fix(mangafox): searching with spaces

---

src/rust/madara/sources/harimanga/res/source.json
src/rust/madara/sources/harimanga/src/lib.rs

fix(harimanga): update url

---

src/rust/wpcomics/Cargo.toml
src/rust/wpcomics/sources/truyenqq/res/source.json
src/rust/wpcomics/sources/truyenqq/src/lib.rs
src/rust/wpcomics/template/src/template.rs

fix(truyenqq): update url and cf handling

---

src/rust/multichan/Cargo.toml
src/rust/multichan/sources/hentaichan/res/source.json
src/rust/multichan/sources/hentaichan/src/lib.rs
src/rust/multichan/sources/mangachan/res/source.json
src/rust/multichan/sources/mangachan/src/lib.rs
src/rust/multichan/sources/yaoichan/res/source.json
src/rust/multichan/sources/yaoichan/src/lib.rs
src/rust/multichan/template/src/helper.rs
src/rust/multichan/template/src/template.rs

closes #420
closes #689
closes #729

fix(multichan): strip base urls from ids better

---

src/rust/ja.rawdevart/res/source.json
src/rust/ja.rawdevart/src/lib.rs
src/rust/ja.rawdevart/src/parser.rs

fix(rawdevart): page server parsing

---

src/rust/mangastream/sources/westmanga/res/source.json
src/rust/mangastream/sources/westmanga/src/lib.rs

fix(westmanga): update url

---

src/rust/mangastream/Cargo.lock
src/rust/mangastream/sources/aresmanga/Cargo.toml
src/rust/mangastream/sources/aresmanga/res/source.json
src/rust/mangastream/sources/aresmanga/src/lib.rs

fix(aresmanga): parse base64 page data

---

src/rust/en.weebcentral/res/source.json
src/rust/en.weebcentral/src/lib.rs

fix(weebcentral): search items

---

src/rust/madara/sources/toonily/res/source.json
src/rust/madara/sources/toonily/src/lib.rs
src/rust/madara/template/src/helper.rs
src/rust/madara/template/src/template.rs

just cleaned the template a bit as well
closes #908

fix(toonily): update url path

---

src/rust/en.reaperscans/res/source.json
src/rust/en.reaperscans/src/parser.rs

fix(reaperscans): update chapters request

---

src/rust/madara/sources/hentaicb/res/source.json
src/rust/madara/sources/hentaicb/src/lib.rs

fix(hentaicb): update url

---

src/rust/madara/sources/theblank/res/source.json
src/rust/madara/sources/theblank/src/lib.rs

fix(theblank): remove custom user agent

---

src/rust/ru.desu/README.md
src/rust/ru.desu/res/source.json
src/rust/ru.desu/src/constants.rs

fix(ru.desu): switched to a new domain

---

src/rust/uk.mangainua/res/source.json
src/rust/uk.mangainua/src/lib.rs

fix(mangainua): chapter and page lists

---

src/rust/madara/sources/firstkissmanga/res/source.json
src/rust/madara/sources/firstkissmanga/src/lib.rs

fix 1stkissmanga link

---

src/rust/multi.webtoon/res/source.json
src/rust/multi.webtoon/src/helper.rs
src/rust/multi.webtoon/src/lib.rs
src/rust/multi.webtoon/src/parser.rs

bare minimum fixes in order to get the webtoons source working again
closes #993

fix(webtoon): update site parsing

---

src/rust/mangabox/sources/mangabat/res/source.json
src/rust/mangabox/sources/manganato/res/source.json
src/rust/mangabox/template/src/template.rs

Fixes the CloudFlare popup when searching.

fix(mangabox): add referer header

---

src/rust/zh.manhuagui/res/settings.json
src/rust/zh.manhuagui/res/source.json
src/rust/zh.manhuagui/src/lib.rs
src/rust/zh.manhuagui/src/parser.rs

fix(manhuagui): pass desktop requests to fix the mobile response
